# Generated by Django 4.2.13 on 2024-06-07 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingid', models.AutoField(db_column='ratingId', primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('user1', models.ForeignKey(db_column='user1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(db_column='user2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rating_user2_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
            },
        ),
    ]
